[tox]
env_list = py311, linters
no_package = true

[testenv]
base_python = python3.11
commands = pytest --junitxml=unit-tests.xml --cov=wazo_sdk --cov-report=term --cov-report=xml:coverage.xml {posargs} wazo_sdk
deps =
    -rrequirements.txt
    pytest>=9.0.0
    pytest-cov

[testenv:linters]
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files
